### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by windischb** [UXAspects/UXAspects#476]
Have anybody tried to use this Framework in Angular 5?
Are there any changes necessary for the UpgradeAdapter or something??

**Comment by ashley-hunter** [comment]
We have updated our components to be fully compatible with Angular 5 and AOT compilation.

Changes aren't necessary to the upgradeAdapter, however if you are intending to use AOT compilation it would be beneficial to switch to use the UpgradeModule from '@angular/upgrade/static' rather than the upgradeAdapter from '@angular/upgrade'. But as mentioned, this is not an essential step.

**Comment by donna-marijne** [comment]
The [Seed Project](https://github.com/UXAspects/UXAspects-Seed) now shows how to use UX Aspects in an Angular 5 environment. The [upgrade guide](https://github.com/UXAspects/UXAspects/blob/develop/guides/angular-upgrade-guide.md) has been updated to cover the new Angular 5 features.
